spring:
  application:
    name: spring-webflux-demo
  webflux:
    hidden method:
      filter:
        enabled: true
  data:
    mongodb:
      database: test
      port: 27017
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2


logging:
  level:
    org:
      springframework:
        data: TRACE
  # tag::hidden[]
# end::hidden[]

management:
  endpoints:
    web:
      exposure:
        include : "*"
  endpoint:
    health:
      show-details: always
      enabled: true
  info:
    os:
      enabled: true
    java:
      enabled: true
    env:
      enabled: true


info:
  application:
    name: ${spring.application.name}
    description: Very cool Spring Boot application
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'