spring:
  application:
    name: spring-webflux-demo
  webflux:
    hiddenmethod:
      filter:
        enabled: true
  data:
    mongodb:
      database: test
      port: 27017
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

logging:
  level:
    org:
      springframework:
        data: TRACE
  # tag::hidden[]
# end::hidden[]
